std1 = input("Enter marks of student 1:")
std2 = input("Enter marks of student 2:")
std3 = input("Enter marks of student 3:")
std4 = input("Enter marks of student 4:")
std5 = input("Enter marks of student 5:")
std6 = input("Enter marks of student 6:")
std1 = int(std1)
std2 = int(std2)
std3 = int(std3)
std4 = int(std4)
std5 = int(std5)
std6 = int(std6)
student = [std1, std2, std3, std4, std5, std6]
student.sort()
print(student)
